

semantic_feature_mft_v1  = {
    "care_beneficial": [
      "The belief that government should ensure ACCESSIBLE HEALTHCARE and SOCIAL SERVICES for all citizens, particularly focusing on VULNERABLE POPULATIONS like children, women, and disadvantaged groups. This perspective emphasizes COLLECTIVE RESPONSIBILITY for wellbeing through PUBLIC FUNDING mechanisms, PREVENTATIVE CARE programs, and COMPREHENSIVE SUPPORT systems that address both physical and mental health needs. It values UNIVERSAL COVERAGE approaches that remove financial barriers to treatment, promotes EQUITABLE DISTRIBUTION of medical resources, and considers healthcare a FUNDAMENTAL RIGHT rather than a privilege based on economic status."
    ],
    "care_harmful": [
      "The recognition that certain issues like GUN VIOLENCE, ENVIRONMENTAL DEGRADATION, and CLIMATE CHANGE pose significant THREATS to human life, health, and wellbeing that require immediate intervention. This view emphasizes the HARMFUL CONSEQUENCES of inaction, the URGENT RISKS facing communities, and the need for PROTECTIVE MEASURES to prevent SUFFERING and DAMAGE to public health. It prioritizes PREVENTATIVE REGULATION to address root causes of harm, supports EVIDENCE-BASED POLICIES to mitigate dangers, and advocates for SYSTEMIC SOLUTIONS to complex problems that endanger citizens' safety and future generations' welfare."
    ],
    "fairness_beneficial": [
      "The conviction that ECONOMIC EQUALITY requires policies like HIGHER MINIMUM WAGE, STRONGER UNIONS, HIGHER TAXES ON THE RICH, and an EXPANDED SOCIAL SAFETY NET to ensure everyone can THRIVE regardless of background. This perspective emphasizes REDISTRIBUTIVE JUSTICE mechanisms that narrow wealth gaps, EQUAL OPPORTUNITY frameworks that level playing fields, and STRUCTURAL REFORMS that address historical inequities. It supports PROGRESSIVE TAXATION systems that ask more from those with greater resources, EQUITABLE RESOURCE allocation across society, and INCLUSIVE ECONOMIC policies that prioritize broad-based prosperity over concentrated wealth accumulation."
    ],
    "fairness_harmful": [
      "The concern that certain policies create DISPROPORTIONATE BENEFITS for specific groups while imposing burdens on others, and that DEI IDEOLOGY undermines traditional values of MERIT, FAIRNESS, and EQUALITY under the law. This view emphasizes problems with REVERSE DISCRIMINATION, PREFERENTIAL TREATMENT based on identity characteristics, UNEARNED ADVANTAGES given to certain demographics, and how QUOTA SYSTEMS can violate principles of individual achievement. It values EQUAL TREATMENT regardless of background, COMPETITIVE PROCESSES based on objective criteria, and NEUTRAL STANDARDS that don't favor particular groups at others' expense in educational, employment, and governmental contexts."
    ],
    "loyalty_beneficial": [
      "The view that STRONG ALLIANCES and INTERNATIONAL COOPERATION enhance national security and that a POWERFUL NATIONAL DEFENSE provides increased security and peace. This perspective values PATRIOTIC UNITY that transcends partisan divisions, COLLECTIVE SOLIDARITY among citizens toward shared national goals, INSTITUTIONAL COMMITMENT to democratic principles, and DIPLOMATIC PARTNERSHIPS that strengthen America's position globally. It emphasizes MULTILATERAL APPROACHES to solving international problems, COALITION BUILDING with like-minded nations, MUTUAL DEFENSE arrangements that deter aggression, and MILITARY READINESS that protects shared interests while maintaining America's leadership role in world affairs."
    ],
    "loyalty_harmful": [
      "The belief that BORDER SECURITY is fundamental to national identity and that the government's FIRST OBLIGATION is to provide for the COMMON DEFENSE of the United States against external threats. This view emphasizes NATIONAL SOVEREIGNTY as paramount, TERRITORIAL INTEGRITY as non-negotiable, AMERICA FIRST policies that prioritize domestic interests, IMMIGRATION CONTROL as essential to preserving cultural cohesion, and PROTECTIVE BARRIERS against foreign influences that might undermine domestic stability. It values PATRIOTIC ALLEGIANCE to country above international commitments, STRONG BORDERS as prerequisites for national security, and VIGILANT PROTECTION of American interests against potential adversaries or unrestricted migration."
    ],
    "authority_beneficial": [
      "The perspective that a PROMINENT AND POWERFUL GOVERNMENT is necessary to REGULATE BUSINESS and ensure WELFARE AND EQUALITY for all citizens. This view supports STRONG OVERSIGHT of markets to prevent exploitation, CENTRALIZED PLANNING of key economic sectors to ensure fairness, EXPERT ADMINISTRATION of public programs to maximize efficiency, HIERARCHICAL STRUCTURES that maintain social order, and GOVERNMENTAL AUTHORITY to intervene when necessary to protect public interests. It values REGULATORY FRAMEWORKS that constrain corporate power, COORDINATED RESPONSES to societal challenges, STANDARDIZED RULES that create predictable environments, and INSTITUTIONAL LEADERSHIP that guides national development toward collective prosperity rather than individual gain."
    ],
    "authority_harmful": [
      "The conviction that GOVERNMENT INTERFERENCE should be minimized in favor of INDIVIDUAL LIBERTY, FREE MARKETS, and LIMITED GOVERNMENT operating only by the CONSENT OF THE GOVERNED. This perspective emphasizes PERSONAL AUTONOMY in decision-making, DEREGULATION of business activities to promote growth, CONSTITUTIONAL CONSTRAINTS on state power, DECENTRALIZED DECISION-MAKING at local levels, and VOLUNTARY ASSOCIATION as preferable to mandated participation. It values FEDERALISM that distributes authority away from central government, SEPARATION OF POWERS that prevents concentration of control, REDUCED BUREAUCRACY that minimizes administrative burdens, and MARKET SOLUTIONS to social problems rather than government interventions that restrict freedom and economic dynamism."
    ],
    "sanctity_beneficial": [
      "The adherence to PRO-LIFE positions, TRADITIONAL FAMILY VALUES, and the need for RELIGIOUS PROTECTION against perceived attacks on faith by governments. This perspective emphasizes MORAL PURITY in public policy decisions, SACRED TRADITIONS that should be preserved in society, NATURAL ORDER in human relationships and social structures, SPIRITUAL FOUNDATIONS for ethical decisions, and REVERENCE FOR LIFE from conception. It values RELIGIOUS LIBERTY as a fundamental right, TRADITIONAL MARRIAGE as the cornerstone of society, MORAL ABSOLUTES that transcend cultural trends, SANCTITY OF HUMAN LIFE at all stages, and FAITH-BASED PRINCIPLES as essential guides for personal conduct and public governance."
    ],
    "sanctity_harmful": [
      "The support for SEPARATION OF CHURCH AND STATE, women's rights to FREE ABORTION, LGBTQ+ RIGHTS to equal treatment, and addressing CLIMATE CHANGE as a moral imperative. This view emphasizes BODILY AUTONOMY in reproductive decisions, SECULAR GOVERNANCE principles that prevent religious domination, ENVIRONMENTAL STEWARDSHIP as an ethical obligation to future generations, REPRODUCTIVE FREEDOM as a fundamental right, and INCLUSIVE RECOGNITION of diverse family structures and gender identities. It values SCIENTIFIC CONSENSUS over religious doctrine in policy formation, PERSONAL CHOICE in matters of conscience, ECOLOGICAL PRESERVATION as a sacred duty, and EQUAL DIGNITY for all relationship forms regardless of traditional religious prescriptions."
    ],
    "liberty_beneficial": [
      "The championing of INDIVIDUAL FREEDOM, STATES' RIGHTS, the RIGHT TO BEAR ARMS, and STRUCTURAL INDEPENDENCE from arbitrary power as essential components of a free society. This perspective values PERSONAL RESPONSIBILITY for one's choices and outcomes, MINIMAL INTERFERENCE in private decisions by government entities, CONSTITUTIONAL PROTECTIONS against overreach, VOLUNTARY EXCHANGE in economic matters, and SELF-DETERMINATION as the foundation for human dignity. It emphasizes LIMITED GOVERNMENT that serves rather than directs citizens, FREE ENTERPRISE systems that allow economic mobility, PROPERTY RIGHTS that secure individual autonomy, and NEGATIVE LIBERTIES that protect against coercion rather than entitling specific outcomes or benefits from others."
    ],
    "liberty_harmful": [
      "The promotion of DIVERSITY, EQUITY, AND INCLUSION frameworks to ensure FAIR TREATMENT and FULL PARTICIPATION of all people, particularly historically UNDERREPRESENTED groups, free from DISCRIMINATION AND HARASSMENT. This view emphasizes COLLECTIVE LIBERATION from systemic barriers, STRUCTURAL REFORMS to address historical inequities, PROTECTED STATUS for vulnerable populations, EQUAL ACCESS to opportunities regardless of background, and POSITIVE RIGHTS that require active intervention to secure. It values AFFIRMATIVE MEASURES to counteract embedded disadvantages, REDISTRIBUTIVE POLICIES that level playing fields, COMMUNITY EMPOWERMENT over individualistic approaches, SOCIAL JUSTICE as prerequisite for meaningful freedom, and GOVERNMENTAL SAFEGUARDS against majority tyranny or market-based exclusion."
    ]
  }


semantic_feature_mft_v2 = {
    'care_beneficial': ["Emphasizing COLLECTIVE WELFARE, SOCIAL PROGRAMS, and GOVERNMENT INTERVENTION as essential for addressing societal needs. Policies prioritize UNIVERSAL HEALTHCARE, ENVIRONMENTAL PROTECTION, and SAFETY NETS for vulnerable populations. This perspective views COMMUNITY WELLBEING as a shared responsibility requiring coordinated public action rather than individual solutions. Government is seen as a positive force for ensuring EQUITABLE ACCESS to resources, PREVENTATIVE CARE, and services that protect citizens from harm. The focus is on SYSTEMIC SOLUTIONS to care-related challenges, with an understanding that REGULATORY FRAMEWORKS are necessary to ensure corporations and institutions act in the public interest."],
    
    'care_harmful': ["Prioritizing INDIVIDUAL RESPONSIBILITY, PERSONAL CHOICE, and LIMITED GOVERNMENT in addressing welfare concerns. This perspective emphasizes SELF-RELIANCE, PRIVATE CHARITY, and MARKET-BASED SOLUTIONS as more effective than government programs. NATIONAL DEFENSE and BORDER SECURITY are viewed as primary care responsibilities of government, while social welfare is better handled through VOLUNTARY ASSOCIATION and FAMILY STRUCTURES. Government intervention in healthcare and social services is seen as creating DEPENDENCY and INEFFICIENCY, undermining personal initiative and community-based solutions. ECONOMIC FREEDOM is considered essential for enabling individuals to meet their own needs without bureaucratic interference."],
    
    'fairness_beneficial': ["Advocating for ECONOMIC JUSTICE through WEALTH REDISTRIBUTION, PROGRESSIVE TAXATION, and STRUCTURAL REFORMS that address historical inequities. This perspective emphasizes EQUAL OUTCOMES across different demographic groups as the measure of true fairness. AFFIRMATIVE ACTION and TARGETED INTERVENTIONS are seen as necessary corrections to systemic advantages and disadvantages. LABOR PROTECTIONS and COLLECTIVE BARGAINING are viewed as essential counterbalances to corporate power. Government's role includes ensuring EQUITABLE DISTRIBUTION of resources and opportunities, with particular attention to MARGINALIZED COMMUNITIES whose needs require special consideration to achieve substantive rather than merely formal equality."],
    
    'fairness_harmful': ["Championing EQUAL OPPORTUNITY, MERITOCRACY, and PROCEDURAL JUSTICE as the foundations of fairness. This perspective emphasizes CONSISTENT RULES applied regardless of group identity, with success determined by INDIVIDUAL MERIT and effort rather than predetermined outcomes. ECONOMIC LIBERTY and FREE MARKET COMPETITION are seen as the most impartial mechanisms for distributing rewards based on contribution. PERSONAL ACHIEVEMENT is valued over group-based considerations, with REDUCED REGULATION allowing natural talents and work ethic to determine one's position. Government's role should be limited to ensuring NEUTRAL PROCESSES rather than engineering specific results, as attempts to guarantee equal outcomes inevitably create new forms of unfairness."],
    
    'loyalty_beneficial': ["Embracing GLOBAL CITIZENSHIP, INTERNATIONAL COOPERATION, and MULTICULTURAL INTEGRATION as expressions of expanded loyalty beyond national boundaries. This perspective values DIPLOMATIC ALLIANCES and MULTILATERAL AGREEMENTS as essential for addressing transnational challenges like climate change and human rights. IMMIGRANT INCLUSION is seen as strengthening rather than threatening national identity, with CULTURAL DIVERSITY celebrated as a source of innovation and resilience. HUMANITARIAN CONCERNS take precedence over narrow national interests, reflecting a commitment to UNIVERSAL VALUES and SHARED RESPONSIBILITY for global wellbeing. Loyalty extends to future generations through SUSTAINABLE POLICIES and long-term thinking."],
    
    'loyalty_harmful': ["Emphasizing NATIONAL SOVEREIGNTY, PATRIOTIC VALUES, and CULTURAL PRESERVATION as primary expressions of loyalty. This perspective prioritizes AMERICA FIRST policies that protect citizens' interests above international commitments. BORDER SECURITY and IMMIGRATION CONTROL are viewed as essential for maintaining national identity and social cohesion. ECONOMIC PROTECTIONISM is favored to benefit domestic workers and industries over global market efficiency. INDEPENDENT DECISION-MAKING in foreign affairs is valued over multilateral constraints, with MILITARY READINESS seen as the ultimate guarantee of security. Loyalty is directed toward one's country, TRADITIONAL HERITAGE, and fellow citizens rather than abstract global ideals or foreign populations."],
    
    'authority_beneficial': ["Advocating for STRONG REGULATORY FRAMEWORKS, GOVERNMENT OVERSIGHT, and INSTITUTIONAL EXPERTISE to address complex societal challenges. This perspective values CENTRALIZED PLANNING and COORDINATED ACTION as necessary for implementing comprehensive solutions to problems like climate change and economic inequality. CORPORATE ACCOUNTABILITY and CONSUMER PROTECTIONS are seen as essential counterbalances to market power. LABOR UNIONS and PROFESSIONAL STANDARDS provide important structural authority that ensures fair treatment and quality outcomes. SCIENTIFIC CONSENSUS guides policy decisions, with TECHNICAL SPECIALISTS given significant influence in their areas of competence. Authority is legitimate when it serves collective interests and protects vulnerable populations."],
    
    'authority_harmful': ["Promoting DECENTRALIZED GOVERNANCE, CONSTITUTIONAL LIMITS on power, and INDIVIDUAL AUTONOMY against overreaching authority. This perspective values FEDERALISM and LOCAL CONTROL over centralized decision-making, allowing for diverse approaches tailored to specific communities. MARKET SOLUTIONS and VOLUNTARY COOPERATION are preferred to top-down mandates, with PRIVATE ENTERPRISE seen as more responsive and efficient than government bureaucracy. SEPARATION OF POWERS and CHECKS AND BALANCES prevent the concentration of authority in any single institution. PERSONAL LIBERTY requires SKEPTICISM toward expert claims and resistance to administrative expansion. Authority is legitimate only when narrowly defined, transparently exercised, and subject to democratic accountability through regular electoral processes."],
    
    'sanctity_beneficial': ["Upholding BODILY AUTONOMY, REPRODUCTIVE RIGHTS, and PERSONAL DIGNITY as sacred principles deserving protection. This perspective values SCIENTIFIC EVIDENCE and SECULAR GOVERNANCE as foundations for policy decisions affecting health and personal choices. ENVIRONMENTAL STEWARDSHIP is treated with moral urgency, reflecting reverence for natural systems and future generations. LGBTQ+ EQUALITY is affirmed as consistent with human dignity and self-determination. INCLUSIVE RECOGNITION of diverse relationships and identities is seen as respecting the inherent worth of all persons. The separation of church and state is maintained to protect both religious freedom and civic equality, with EVIDENCE-BASED APPROACHES preferred over tradition-based restrictions on individual choices."],
    
    'sanctity_harmful': ["Preserving TRADITIONAL VALUES, RELIGIOUS LIBERTY, and NATURAL ORDER as sacred principles that should guide personal and public life. This perspective emphasizes PRO-LIFE PROTECTIONS for unborn children and respect for divinely established MORAL BOUNDARIES. FAMILY STRUCTURE based on conventional marriage is viewed as the fundamental social unit deserving special recognition and support. FAITH-BASED PERSPECTIVES should inform public policy on matters of morality and human nature. PARENTAL AUTHORITY in education and child-rearing takes precedence over state intervention or progressive social engineering. CONVENTIONAL GENDER ROLES reflect biological realities and time-tested wisdom rather than arbitrary social constructs. Sanctity requires maintaining clear distinctions between categories established by nature or divine law."],
    
    'liberty_beneficial': ["Advancing FREEDOM FROM DISCRIMINATION, CIVIL RIGHTS PROTECTIONS, and EQUAL OPPORTUNITY as essential components of true liberty. This perspective recognizes that meaningful freedom requires GOVERNMENT SAFEGUARDS against powerful private interests that can restrict individual choices. COLLECTIVE BARGAINING and WORKER PROTECTIONS ensure economic liberty extends beyond employers to employees. SOCIAL JUSTICE initiatives address structural barriers that prevent full participation in society. REGULATORY OVERSIGHT of markets prevents exploitation and ensures fair competition. Liberty is understood as requiring both NEGATIVE FREEDOMS (absence of interference) and POSITIVE FREEDOMS (access to resources and opportunities), with particular attention to removing obstacles faced by historically marginalized groups."],
    
    'liberty_harmful': ["Defending INDIVIDUAL AUTONOMY, CONSTITUTIONAL RIGHTS, and MINIMAL GOVERNMENT as the foundations of liberty. This perspective emphasizes NEGATIVE FREEDOMS—protection from interference rather than entitlements to support. PRIVATE PROPERTY RIGHTS and ECONOMIC FREEDOM are seen as essential expressions of personal liberty, with DEREGULATION allowing individuals and businesses to make decisions without bureaucratic constraints. SECOND AMENDMENT PROTECTIONS safeguard the fundamental right to self-defense. FREE SPEECH must be preserved even when controversial or offensive. RELIGIOUS FREEDOM includes the right to live according to one's faith in public and private life. Liberty requires PERSONAL RESPONSIBILITY and acceptance of natural consequences rather than government intervention to equalize outcomes."]
}


semantic_features_mft_v3 = {
    'care_beneficial': ["Advocacy for QUALITY, AFFORDABLE healthcare focused on PATIENT WELLBEING and PREVENTATIVE measures, ensuring UNIVERSAL ACCESS for vulnerable populations while respecting INDIVIDUAL CHOICE in treatment options. This approach views healthcare as a FUNDAMENTAL RIGHT requiring COMPASSIONATE delivery and SUPPORTIVE systems that address both physical and mental health concerns through collaborative, patient-centered models that prioritize POSITIVE OUTCOMES and EQUITABLE DISTRIBUTION of medical resources to maximize community health."],
    
    'care_harmful': ["Recognition of EXISTENTIAL THREATS to public health including PREVENTABLE DISEASES and ENVIRONMENTAL HAZARDS that cause widespread SUFFERING, requiring immediate PROTECTIVE measures and INTERVENTION strategies to address imminent dangers. This perspective emphasizes RISK REDUCTION and HARM PREVENTION through systematic approaches that identify and mitigate factors contributing to negative health outcomes, community vulnerability, and COLLECTIVE DAMAGE, viewing inaction as a form of negligence that perpetuates avoidable harm to vulnerable populations."],
    
    'fairness_beneficial': ["Support for EQUITABLE distribution of resources through INCLUSIVE policies that ensure REPRESENTATION of diverse perspectives and OPPORTUNITY for all community members regardless of background. This approach values BALANCED TREATMENT in economic and social systems, promoting ACCESS to institutions and services while recognizing historical DISPARITIES that require targeted interventions to achieve meaningful equality. It emphasizes STRUCTURAL REFORMS that address systemic barriers and create pathways for marginalized groups to participate fully in society."],
    
    'fairness_harmful': ["Emphasis on MERIT-BASED advancement and EQUAL TREATMENT under law without special considerations based on group identity, maintaining CONSISTENT STANDARDS across all demographics. This perspective values INDIVIDUAL ACHIEVEMENT and PERSONAL RESPONSIBILITY as primary determinants of success, opposing PREFERENTIAL POLICIES that treat groups differently based on characteristics rather than objective performance measures. It prioritizes PROCEDURAL FAIRNESS where rules apply uniformly regardless of outcome disparities, viewing differential treatment as undermining genuine equality."],
    
    'liberty_beneficial': ["Affirmation of PERSONAL AUTONOMY and FREEDOM OF CHOICE in private decisions without government interference, emphasizing INDIVIDUAL RIGHTS and LIMITED RESTRICTIONS on economic activities and personal behavior. This approach values SELF-DETERMINATION and VOLUNTARY ASSOCIATION as fundamental principles, supporting REDUCED REGULATION that allows people to pursue their own interests with minimal external constraints. It prioritizes NEGATIVE LIBERTY where absence of coercion enables authentic expression of personal preferences and market-driven solutions to social challenges."],
    
    'liberty_harmful': ["Recognition that STRUCTURAL BARRIERS and SYSTEMIC INEQUALITIES limit genuine freedom for marginalized groups, requiring COLLECTIVE ACTION and PROTECTIVE REGULATIONS to ensure meaningful liberty for all. This perspective emphasizes EQUAL ACCESS and FREEDOM FROM DISCRIMINATION as essential components of true liberty, supporting interventions that address power imbalances that prevent full participation in society. It values POSITIVE LIBERTY where individuals have actual capacity and resources to exercise choices, not merely theoretical freedom from interference."],
    
    'authority_beneficial': ["Advocacy for STRONG LEADERSHIP and CLEAR HIERARCHIES that maintain SOCIAL ORDER and TRADITIONAL VALUES through established institutions with recognized legitimacy. This approach respects LEGITIMATE AUTHORITY derived from expertise, tradition, or democratic processes, valuing STRUCTURED SYSTEMS that provide stability and predictable governance through defined responsibilities and accountability mechanisms. It emphasizes EFFECTIVE GOVERNANCE that coordinates complex social functions, maintains security, and preserves cultural continuity through respected leadership positions and institutional frameworks."],
    
    'authority_harmful': ["Preference for HORIZONTAL ORGANIZATION and DISTRIBUTED POWER that minimizes centralized control, emphasizing INDIVIDUAL AUTONOMY and COMMUNITY DECISION-MAKING at local levels. This perspective values QUESTIONING AUTHORITY and CHALLENGING HIERARCHIES that concentrate power in few hands, supporting systems that distribute influence broadly and enable direct participation in governance rather than deference to established leadership. It prioritizes BOTTOM-UP SOLUTIONS where communities determine their own needs without imposing uniform standards from distant authorities."],
    
    'sanctity_beneficial': ["Emphasis on RELIGIOUS TRADITIONS and MORAL BOUNDARIES that preserve SACRED VALUES and SPIRITUAL INTEGRITY against corrupting influences in modern society. This approach respects LIFE'S SANCTITY from conception and defends TRADITIONAL MARRIAGE as divinely ordained institutions, maintaining clear distinctions between pure and impure practices while protecting cultural and religious heritage from degradation. It values TRANSCENDENT PRINCIPLES that guide ethical decisions beyond material considerations, honoring practices that maintain moral purity and spiritual wholeness."],
    
    'sanctity_harmful': ["Prioritization of SCIENTIFIC EVIDENCE and PRAGMATIC SOLUTIONS to social challenges, viewing PERSONAL CHOICE and BODILY AUTONOMY as paramount in reproductive and lifestyle decisions. This perspective emphasizes ENVIRONMENTAL PROTECTION and SUSTAINABLE PRACTICES as ethical imperatives for preserving natural systems, approaching moral questions through rational analysis rather than traditional prohibitions. It values EVIDENCE-BASED POLICIES that address concrete harms rather than abstract purity concerns, rejecting restrictions based solely on religious doctrine or traditional taboos."],
    
    'loyalty_beneficial': ["STEADFAST COMMITMENT to national interests and PATRIOTIC VALUES that prioritize AMERICAN SOVEREIGNTY and BORDER SECURITY as fundamental responsibilities of government. This approach values NATIONAL UNITY and CULTURAL COHESION, emphasizing ALLEGIANCE to country above international obligations and maintaining STRONG DEFENSE of territorial integrity against external threats. It promotes SHARED IDENTITY based on common history and values, viewing national loyalty as essential for collective security and prosperity in a competitive global environment."],
    
    'loyalty_harmful': ["Emphasis on GLOBAL COOPERATION and INTERNATIONAL AGREEMENTS that address shared challenges through MULTILATERAL FRAMEWORKS and COLLABORATIVE SOLUTIONS across borders. This perspective values DIVERSE PERSPECTIVES and INCLUSIVE COMMUNITIES that transcend national boundaries, supporting HUMANITARIAN CONCERNS and UNIVERSAL RIGHTS that may sometimes require subordinating narrow national interests to broader human welfare. It prioritizes TRANSNATIONAL SOLIDARITY on issues like climate change and human rights, viewing global interdependence as necessary for addressing complex modern challenges."]
}

#były wczytane wytyczne do promtu o polaryzacji
semantic_features_mft_v4 = {
    'care_beneficial': ["The belief that collective WELLBEING is a societal priority, emphasizing government's role in providing universal ACCESS to HEALTHCARE, SOCIAL SERVICES, and PROTECTION for vulnerable populations. This perspective values comprehensive SUPPORT systems that address both immediate and long-term needs, including ENVIRONMENTAL safeguards, preventative care, and crisis intervention. It prioritizes creating robust public infrastructure that ensures all citizens receive necessary resources regardless of socioeconomic status, viewing collective action as essential for promoting community HEALTH and reducing suffering through systematic approaches rather than individual solutions."],
    
    'care_harmful': ["The recognition that HARM prevention requires acknowledging various threats to WELLBEING, including both physical VIOLENCE and threats to unborn LIVES. This perspective emphasizes PROTECTION of the vulnerable through appropriate SAFETY measures, whether addressing gun violence or preserving fetal development. It acknowledges that different groups face distinct risks requiring tailored protective responses, and that genuine care involves recognizing all forms of suffering. This view considers both immediate dangers and long-term consequences, suggesting that comprehensive PROTECTION must account for diverse vulnerabilities rather than privileging certain concerns over others."],
    
    'fairness_beneficial': ["The commitment to creating EQUAL OPPORTUNITIES for all people regardless of background, with particular attention to historically UNDERREPRESENTED groups who have faced systemic barriers. This perspective values INCLUSION as both a moral imperative and practical necessity, promoting FAIR TREATMENT through policies that acknowledge historical inequities while working toward a more balanced future. It emphasizes that genuine equality requires active measures to ensure all individuals can participate fully in society, recognizing that passive approaches often perpetuate existing advantages and disadvantages, and that meaningful FAIRNESS involves both procedural justice and equitable outcomes."],
    
    'fairness_harmful': ["The concern that certain approaches to equality create new forms of UNFAIRNESS by overlooking MERIT-based considerations or creating DISPROPORTIONATE advantages for select groups. This perspective questions whether policies intended to address historical inequities may themselves introduce IMBALANCES that undermine genuine fairness. It suggests that BALANCED approaches should avoid ideological extremes, considering individual effort alongside structural factors, and that true equity requires nuanced solutions rather than rigid formulas. This view emphasizes that fairness involves respecting diverse contributions and avoiding systems that privilege particular identities or perspectives over substantive achievements."],
    
    'loyalty_beneficial': ["The recognition that INTERNATIONAL COOPERATION through formal ALLIANCES and PARTNERSHIPS serves national interests while fostering global stability. This perspective values MULTILATERAL approaches that leverage collective resources and shared objectives, acknowledging that complex challenges often require coordinated responses across borders. It emphasizes that strategic collaboration can amplify national influence and effectiveness, creating mutual BENEFITS that exceed what countries could achieve in isolation. This view recognizes that while maintaining sovereignty remains important, participating in international frameworks allows nations to address transnational issues more effectively while building relationships that enhance security and prosperity for all involved parties."],
    
    'loyalty_harmful': ["The conviction that NATIONAL interests must take priority, emphasizing AMERICA FIRST policies and robust BORDER SECURITY as essential for preserving sovereignty and identity. This perspective values PROTECTION of citizens against external threats, viewing strong boundaries as fundamental to maintaining cultural cohesion and economic security. It emphasizes that a nation's primary obligation is to its own people, suggesting that international engagements should be evaluated primarily through the lens of domestic benefit. This view considers COMMON DEFENSE a core function of government, maintaining that genuine patriotism requires prioritizing national wellbeing over abstract global concerns or foreign interests that may undermine domestic prosperity."],
    
    'authority_strong': ["The belief that GOVERNMENT plays an essential role in addressing societal challenges through appropriate REGULATIONS and WELFARE programs. This perspective views PROMINENT public institutions as necessary counterweights to private power, capable of ensuring collective wellbeing when properly structured and administered. It emphasizes that POWERFUL oversight mechanisms can protect vulnerable populations and promote broader prosperity, suggesting that certain problems require coordinated action beyond individual or market-based solutions. This view acknowledges that while government authority should be exercised judiciously, effective governance requires sufficient capacity to implement policies that serve the public interest across economic, social, and environmental domains."],
    
    'authority_weak': ["The conviction that GOVERNMENT authority must be strictly limited to preserve INDIVIDUAL freedom and economic dynamism, operating only with the explicit CONSENT of the governed. This perspective values decentralized decision-making that empowers BUSINESSES and citizens rather than bureaucratic structures, viewing LEGITIMATE constraints on centralized power as essential safeguards against overreach and inefficiency. It emphasizes that prosperity emerges primarily through voluntary exchanges and private initiative, suggesting that government intervention often creates unintended consequences that undermine both liberty and material wellbeing. This view considers constitutional limitations on authority not as obstacles to progress but as vital protections that enable genuine human flourishing."],
    
    'sanctity_beneficial': ["The appreciation for TRADITIONAL moral frameworks that honor FAMILY structures and RELIGIOUS perspectives as foundational elements of a healthy society. This view acknowledges the importance of PROTECTION for faith-based institutions and their distinctive contributions to community wellbeing, recognizing that RELIGIOUSLY AFFILIATED organizations often provide essential services while embodying deeply held values. It emphasizes that certain principles transcend purely secular considerations, suggesting that genuine pluralism requires respecting diverse spiritual traditions rather than marginalizing them. This perspective considers moral and ethical frameworks rooted in historical wisdom as valuable guides for addressing contemporary challenges, offering insights that purely materialistic approaches may overlook."],
    
    'sanctity_harmful': ["The recognition that maintaining appropriate SEPARATION between CHURCH and STATE protects both religious liberty and civic equality, preventing any faith tradition from dominating public institutions. This perspective acknowledges ENVIRONMENTAL and CLIMATE concerns as morally significant issues requiring serious attention, viewing stewardship of natural resources as an ethical imperative rather than merely a practical consideration. It emphasizes that government neutrality on religious matters ensures all citizens receive equal treatment regardless of their spiritual beliefs, suggesting that public policy should be grounded in broadly accessible reasoning rather than particular theological commitments. This view considers institutional boundaries between religious and governmental spheres as safeguards for both authentic faith and inclusive democracy."],
    
    'liberty_beneficial': ["The conviction that INDIVIDUAL FREEDOM and ECONOMIC choice represent core values that must be protected through appropriate CONSTITUTIONAL safeguards against overreach. This perspective emphasizes personal INDEPENDENCE as essential for human flourishing, viewing rights like the SECOND AMENDMENT as important protections against potential tyranny and defending self-determination across multiple domains. It suggests that genuine liberty requires limiting external constraints on personal decisions, allowing individuals to pursue their own conception of the good life without unnecessary interference. This view considers freedom primarily as freedom from coercion, emphasizing negative liberty and the importance of maintaining spaces where individuals can exercise their judgment without excessive regulation or control."],
    
    'liberty_harmful': ["The understanding that meaningful FREEDOM requires protection FROM various forms of DISCRIMINATION and HARASSMENT that undermine equal participation in society. This perspective emphasizes that personal autonomy includes making one's OWN choices about HEALTH CARE and other intimate matters without external interference, recognizing that liberty encompasses both freedom from government control and freedom from private coercion. It suggests that genuine freedom requires addressing power imbalances that restrict opportunities for marginalized groups, viewing civil rights protections as enhancing rather than limiting liberty. This view considers positive freedom alongside negative freedom, acknowledging that removing formal barriers may be insufficient without addressing substantive obstacles to meaningful choice."]
}